### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by klange** [miguelangelo78/munix-helios#1]
Hello Miguel,

Your sources are derived from [my project](https://github.com/klange/toaruos/), but you've neglected to follow the terms of the license. In particular, you have replaced the license information in the heads of the source files with declarations that you are the author, which is in violation of the requirement that any derived source code or binaries you distribute must carry with them the [license text](https://github.com/klange/toaruos/blob/strawberry-dev/LICENSE.md). Being compliant with a BSD-style license such as this is very simple, and this should be easily rectified. Linking to my project in your README is not sufficient for compliance.

**Comment by miguelangelo78** [comment]
Apologies for this,

All source files for both the kernel and OS projects have been updated with their correspondent headers. Also, the LICENSE.md file has been added.
This was not intentional, as Eclipse generates those headers automatically and grabs the name from my PC account. However, it has been corrected, thanks for pointing out.

And by the way, great work on the OS and kernel, it's looking really good.

**Comment by klange** [comment]
Thanks!

**Comment by klange** [comment]
When you applied license headers to the source files, you incorrectly noted Dave Weiler, a minor contributor to ToaruOS, as the author and owner of all of them, instead of the actual authors, which in the vast majority of cases does not include Dave. I have noticed the same issue in your kernel fork. ToaruOS does not employ a copyright assignment scheme, and so contributors maintain copyright of their individual contributions and license those contributions under the NCSA / University of Illinois license. As such, each file has different authors and requires different headers. You have instead copied and pasted the same header, which appears to be from `kernel/libc.c` or something similar on all of the files.

**Comment by miguelangelo78** [comment]
Wow, I can't believe I messed this up real bad.
It's fixed now.
Thanks and sorry for this.
